name: Workflow Dispatch Form

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
      favorite_lang:
        description: 'Favorite Programming Language'
        required: true
        type: choice
        options:
          - 'C++'
          - 'C#'
          - 'Java'
          - 'Python'
          - 'JavaScript'

jobs:
  print-favorite-lang:
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: |
          echo "Dispatched by ${{github.actor}} with event name ${{github.event_name}}"
          echo "Reading variable name ${{ vars.MY_VARIABLE_NAME }}"
          echo "Hello, my name is ${{inputs.name}}!"
          echo "Favorite Programming Language: ${{inputs.favorite_lang}}"
      - name: Recommend
        if: ${{inputs.favorite_lang == 'C++'}}
        run: |
          echo "Really? I recommend you to learn something more friendly"
  